// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v6.31.0
// source: service.proto

package pricefetcher_grpc_microservices

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Datetime      string                 `protobuf:"bytes,3,opt,name=datetime,proto3" json:"datetime,omitempty"`
	Close         string                 `protobuf:"bytes,4,opt,name=close,proto3" json:"close,omitempty"`
	PercentChange string                 `protobuf:"bytes,5,opt,name=percent_change,json=percentChange,proto3" json:"percent_change,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *PriceResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PriceResponse) GetDatetime() string {
	if x != nil {
		return x.Datetime
	}
	return ""
}

func (x *PriceResponse) GetClose() string {
	if x != nil {
		return x.Close
	}
	return ""
}

func (x *PriceResponse) GetPercentChange() string {
	if x != nil {
		return x.PercentChange
	}
	return ""
}

type SymbolsList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbols       []*PriceRequest        `protobuf:"bytes,1,rep,name=symbols,proto3" json:"symbols,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SymbolsList) Reset() {
	*x = SymbolsList{}
	mi := &file_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SymbolsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SymbolsList) ProtoMessage() {}

func (x *SymbolsList) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SymbolsList.ProtoReflect.Descriptor instead.
func (*SymbolsList) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *SymbolsList) GetSymbols() []*PriceRequest {
	if x != nil {
		return x.Symbols
	}
	return nil
}

var File_service_proto protoreflect.FileDescriptor

const file_service_proto_rawDesc = "" +
	"\n" +
	"\rservice.proto\"&\n" +
	"\fPriceRequest\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\"\x94\x01\n" +
	"\rPriceResponse\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdatetime\x18\x03 \x01(\tR\bdatetime\x12\x14\n" +
	"\x05close\x18\x04 \x01(\tR\x05close\x12%\n" +
	"\x0epercent_change\x18\x05 \x01(\tR\rpercentChange\"6\n" +
	"\vSymbolsList\x12'\n" +
	"\asymbols\x18\x01 \x03(\v2\r.PriceRequestR\asymbols2\xbf\x01\n" +
	"\fPriceFetcher\x12+\n" +
	"\n" +
	"FetchPrice\x12\r.PriceRequest\x1a\x0e.PriceResponse\x12;\n" +
	"\x19FetchPriceServerStreaming\x12\f.SymbolsList\x1a\x0e.PriceResponse0\x01\x12E\n" +
	" FetchPriceBidirectionalStreaming\x12\r.PriceRequest\x1a\x0e.PriceResponse(\x010\x01B6Z4github.com/bruce-mig/pricefetcher-grpc-microservicesb\x06proto3"

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData []byte
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)))
	})
	return file_service_proto_rawDescData
}

var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_service_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: PriceRequest
	(*PriceResponse)(nil), // 1: PriceResponse
	(*SymbolsList)(nil),   // 2: SymbolsList
}
var file_service_proto_depIdxs = []int32{
	0, // 0: SymbolsList.symbols:type_name -> PriceRequest
	0, // 1: PriceFetcher.FetchPrice:input_type -> PriceRequest
	2, // 2: PriceFetcher.FetchPriceServerStreaming:input_type -> SymbolsList
	0, // 3: PriceFetcher.FetchPriceBidirectionalStreaming:input_type -> PriceRequest
	1, // 4: PriceFetcher.FetchPrice:output_type -> PriceResponse
	1, // 5: PriceFetcher.FetchPriceServerStreaming:output_type -> PriceResponse
	1, // 6: PriceFetcher.FetchPriceBidirectionalStreaming:output_type -> PriceResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_service_proto_rawDesc), len(file_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}
